//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlMapper.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlTest() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlMapper.ConsoleApp.XmlTest", typeof(XmlTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;UsersContext&gt;
        ///    &lt;User&gt;
        ///        &lt;FullName&gt;Boris Jonson&lt;/FullName&gt;
        ///        &lt;Login&gt;b.jonson&lt;/Login&gt;
        ///        &lt;Age&gt;50&lt;/Age&gt;
        ///        &lt;BIO&gt;I&apos;m gangster sheet!!!&lt;/BIO&gt;
        ///        &lt;RefItem name=&quot;roles&quot; id=&quot;1&quot;/&gt;
        ///    &lt;/User&gt;
        ///    &lt;Roles id=&quot;1&quot;&gt;
        ///        &lt;Role id=&quot;777&quot; name=&quot;God&quot; description=&quot;God mode all rights&quot;/&gt;
        ///        &lt;Role id=&quot;666&quot; name=&quot;Satan&quot; description=&quot;No more rights!!!&quot;/&gt;
        ///        &lt;Role id=&quot;111&quot; name=&quot;SampleUser&quot; description=&quot;Only read rights&quot;/&gt;
        ///    &lt;/Roles&gt;
        ///&lt;/UsersContext&gt;.
        /// </summary>
        internal static string UserContext {
            get {
                return ResourceManager.GetString("UserContext", resourceCulture);
            }
        }
    }
}
