//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlMapper.Tests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlData() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlMapper.Tests.XmlData", typeof(XmlData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;UsersContext&gt;
        ///	&lt;User&gt;
        ///		&lt;FullName&gt;Alice Smith&lt;/FullName&gt;
        ///		&lt;Login&gt;alice.smith&lt;/Login&gt;
        ///		&lt;Age&gt;30&lt;/Age&gt;
        ///		&lt;BIO&gt;Software Developer&lt;/BIO&gt;
        ///		&lt;IsActive&gt;true&lt;/IsActive&gt;
        ///		&lt;JoinDate&gt;2022-03-15&lt;/JoinDate&gt;
        ///		&lt;Address&gt;
        ///			&lt;Street&gt;Main Street&lt;/Street&gt;
        ///			&lt;City&gt;Springfield&lt;/City&gt;
        ///			&lt;PostalCode&gt;12345&lt;/PostalCode&gt;
        ///		&lt;/Address&gt;
        ///		&lt;Roles&gt;
        ///			&lt;Role id=&apos;101&apos; name=&apos;Admin&apos; description=&apos;Full access&apos;/&gt;
        ///			&lt;Role id=&apos;102&apos; name=&apos;User&apos; description=&apos;Limited access&apos;/&gt;
        ///		&lt;/Roles&gt;
        ///	&lt;/User&gt;
        ///&lt;/UsersContext&gt;.
        /// </summary>
        internal static string UsersContext {
            get {
                return ResourceManager.GetString("UsersContext", resourceCulture);
            }
        }
    }
}
